### ISSUE TITLE
Problem Nimble

### ISSUE THREAD

**Issue by ElijahTikus21** [cybertk/generator-swift-framework#44]
Hi, 

I have a problem when I execute the generator this is the return to my term: 
The following build commands failed:
    CompileSwift normal x86_64 /Users/me/Documents/Developpement/EIP_MUZIN/muzin-app-mobile-ios/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

Thanks, 👍

**Comment by alessandrostone** [comment]
Same here...

```
** BUILD FAILED **


The following build commands failed:
    CompileSwift normal x86_64 /Users/alessandroaresta/Documents/RANDOX/ANANASSO/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (1)
    at emit (events.js:144:17)
    at Immediate._onImmediate (/Users/alessandroaresta/.nvm/versions/io.js/v3.3.1/lib/node_modules/generator-swift-framework/node_modules/yeoman-generator/lib/base.js:446:16)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```
