### ISSUE TITLE
Exception when copy gitignore

### ISSUE THREAD

**Issue by caojianhua** [cybertk/generator-swift-framework#6]
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
AssertionError: Trying to copy from a source that does not exist: /Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/node_modules/yeoman-generator/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at null.<anonymous> (/Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/generators/app/index.js:206:25)
    at Array.forEach (native)
    at module.exports.yeoman.generators.Base.extend.writing.projectFiles (/Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/generators/app/index.js:205:19)
    at /Users/caojianhua/.nvm/versions/node/v0.12.4/lib/node_modules/generator-swift-framework/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by cybertk** [comment]
`.gitignore` is renamed to `.npmignore`, see http://stackoverflow.com/questions/24942161/does-npm-ignore-files-listed-in-gitignore

**Comment by cybertk** [comment]
I tried put a empty `.npmignore` on both root and `generators/app/templates` dir, none is worked. `generators/app/templates/.gitignore` is still renamed to `.npmignore` after `npm install`

``` bash
$ tree -aL 1  /usr/local/lib/node_modules/generator-swift-framework/generators/app/templates/
/usr/local/lib/node_modules/generator-swift-framework/generators/app/templates/
├── .npmignore
├── .travis.yml
├── CONTRIBUTING.md
├── Cartfile.private
├── Cartfile.resolved
├── Example
├── Gemfile
├── Gemfile.lock
├── LICENSE
├── Makefile
├── PROJECT_NAME
├── PROJECT_NAME.podspec
├── PROJECT_NAME.xcodeproj
├── README.md
├── UnitTests
└── script

5 directories, 11 files
```
